### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by terabytesoftw** [wdmg/butterfly.cms#4]
I installed it, it works in PHP 8.1, of course there are many updates to be made, i like the blog, but i can't find a listview or a grid to show the posts, in frontend,  it's a good job.

Thks,

**Comment by alex-wdmg** [comment]
Hi! Thx y! Blog is one of the system modules. Use the configuration example from [Configure section](https://github.com/wdmg/yii2-blog#configure) and [Route settings](https://github.com/wdmg/yii2-blog#routing).

In any case, you should integrate everything related to the frontend into your project yourself. The module is only an administrative interface + routing and does not provide a frontend due to the complexity of implementation for everyone.

**Comment by alex-wdmg** [comment]
QA

**Comment by alex-wdmg** [comment]
answered
